# Refer to the http://arshaw.com/fullcalendar/docs/ to know more about the following options in greater depth

cancan: true
mount_path: "/calendar"
layout: "calendar"
defaultView: 'month'
aspectRatio: 1
# weekends: true
# weekNumbers: false
# weekNumberCalculation: 'iso'
# weekNumberTitle: 'W'
  
# editable: false
# disableDragging: false
# disableResizing: false
# allDayDefault: true
# ignoreTimezone: true
  
# lazyFetching: true
# startParam: 'start'
# endParam: 'end'

# titleFormat:
#   month: 'MMMM yyyy'
#   week: "MMM d[ yyyy]{ '&#8212;'[ MMM] d yyyy}"
#   day: 'dddd, MMM d, yyyy'
# columnFormat:
#   month: 'ddd'
#   week: 'ddd M/d'
#   day: 'dddd M/d'
# timeFormat:
#   '': 'h(:mm)t'  # default
  
# isRTL: false
# firstDay: 0
# monthNames: ['January','February','March','April','May','June','July','August','September','October','November','December']
# monthNamesShort: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
# dayNames: ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
# dayNamesShort: ['Sun','Mon','Tue','Wed','Thu','Fri','Sat']
# buttonText:
#   prev: "<span class='fc-text-arrow'>prev..</span>"
#   next: "<span class='fc-text-arrow'>next..</span>"
#   prevYear: "<span class='fc-text-arrow'>&laquo;</span>"
#   nextYear: "<span class='fc-text-arrow'>&raquo;</span>"
#   today: 'today'
#   month: 'month'
#   week: 'week'
#   day: 'day'
  
# theme: false
# buttonIcons:
#   prev: 'circle-triangle-w'
#   next: 'circle-triangle-e'
# selectable: true
# unselectAuto: true
# dropAccept: '*'
# handleWindowResize: true
